export const UPDATE_CHECKLISTITEM = "UPDATE_CHECKLISTITEM";
export const REFLECT_CHECKLISTITEM_INPUT_CHANGE = "REFLECT_CHECKLISTITEM_INPUT_CHANGE";
export const ADD_CHECKLISTITEM = "ADD_CHECKLISTITEM";
export const REMOVE_CHECKLISTITEM = "REMOVE_CHECKLISTITEM";