export const ADD_CARD = "ADD_CARD";
export const UPDATE_CARD = "UPDATE_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const MOVE_CARD = "MOVE_CARD";

export const ADD_CHECKLISTITEM = "ADD_CHECKLISTITEM";
export const UPDATE_CHECKLISTITEM = "UPDATE_CHECKLISTITEM";
export const DELETE_CHECKLISTITEM = "DELETE_CHECKLISTITEM";

export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";