export const TOGGLE_CARD_EDIT_MODE = "TOGGLE_CARD_EDIT_MODE";
export const REFLECT_INPUT_CHANGE = "REFLECT_INPUT_CHANGE";
export const TOGGLE_TITLE_EDITABLE = "TOGGLE_TITLE_EDITABLE";
export const TOGGLE_DESCRIPTION_EDITABLE = "TOGGLE_DESCRIPTION_EDITABLE";
export const TOGGLE_DUEDATE_EDITABLE = "TOGGLE_DUEDATE_EDITABLE";