export const TOGGLE_CARD_EDIT_MODE = "TOGGLE_CARD_EDIT_MODE";
export const TOGGLE_TITLE_EDIT_MODE = "TOGGLE_TITLE_EDIT_MODE";
export const TOGGLE_DESCRIPTION_EDIT_MODE = "TOGGLE_DESCRIPTION_EDIT_MODE";
export const TOGGLE_DUEDATE_EDIT_MODE = "TOGGLE_DUEDATE_EDIT_MODE";

export const REFLECT_TITLE_INPUT_CHANGE = "REFLECT_TITLE_INPUT_CHANGE";
export const REFLECT_DESCRIPTION_INPUT_CHANGE = "REFLECT_DESCRIPTION_INPUT_CHANGE";
export const REFLECT_DUEDATE_INPUT_CHANGE = "REFLECT_DUEDATE_INPUT_CHANGE";

//export const REFLECT_INPUT_CHANGE = "REFLECT_INPUT_CHANGE";