export const CHANGE_CARDID_FOR_EDIT_MODAL = "CHANGE_CARDID_FOR_EDIT_MODAL";
export const TOGGLE_TITLE_EDIT_MODE = "TOGGLE_TITLE_EDIT_MODE";
export const TOGGLE_DESCRIPTION_EDIT_MODE = "TOGGLE_DESCRIPTION_EDIT_MODE";
export const TOGGLE_DUEDATE_EDIT_MODE = "TOGGLE_DUEDATE_EDIT_MODE";
export const CHANGE_EDITABLE_CHECKLISTITEM_ID = "CHANGE_EDITABLE_CHECKLISTITEM_ID";
export const CHANGE_EDITABLE_ADD_CARD = "CHANGE_EDITABLE_ADD_CARD";
export const TOGGLE_ADD_CHECKLISTITEM_EDIT_MODE = "TOGGLE_ADD_CHECKLISTITEM_EDIT_MODE";
export const CHANGE_ITEMID_FOR_DELETE_BUTTON = "CHANGE_ITEMID_FOR_DELETE_BUTTON";